//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRP.Datos
{
    using GRP.Entidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_CRPEntities : DbContext
    {
        public BD_CRPEntities()
            : base("name=BD_CRPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Venta> T_Venta { get; set; }
        public virtual DbSet<T_Articulo> T_Articulo { get; set; }
        public virtual DbSet<T_ArticuloProducto> T_ArticuloProducto { get; set; }
        public virtual DbSet<T_Carta> T_Carta { get; set; }
        public virtual DbSet<T_Combo> T_Combo { get; set; }
        public virtual DbSet<T_ComboVenta> T_ComboVenta { get; set; }
        public virtual DbSet<T_InformacionNutricional> T_InformacionNutricional { get; set; }
        public virtual DbSet<T_Producto> T_Producto { get; set; }
    }
}
