//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRP.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Articulo()
        {
            this.T_ArticuloProducto = new HashSet<T_ArticuloProducto>();
            this.T_InformacionNutricional = new HashSet<T_InformacionNutricional>();
        }
    
        public int codArticulo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string unidadMedida { get; set; }
        public string tipoArticulo { get; set; }
        public short costoxUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ArticuloProducto> T_ArticuloProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_InformacionNutricional> T_InformacionNutricional { get; set; }
    }
}
