//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRP.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ArticuloProducto
    {
        public int cantidad { get; set; }
        public short costo { get; set; }
        public int codProducto { get; set; }
        public int codArticulo { get; set; }
    
        public virtual T_Articulo T_Articulo { get; set; }
        public virtual T_Producto T_Producto { get; set; }
    }
}
