//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRP.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ComboVenta
    {
        public int cantidad { get; set; }
        public short monto { get; set; }
        public int codVenta { get; set; }
        public int codCombo { get; set; }
    
        public virtual T_Combo T_Combo { get; set; }
        public virtual T_Venta T_Venta { get; set; }
    }
}
