//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRP.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_InformacionNutricional
    {
        public int codigoInfNut { get; set; }
        public short calorias { get; set; }
        public short proteinas { get; set; }
        public short carbohidratos { get; set; }
        public short grasas { get; set; }
        public int codArticulo { get; set; }
    
        public virtual T_Articulo T_Articulo { get; set; }
    }
}
