//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRP.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Venta()
        {
            this.T_ComboVenta = new HashSet<T_ComboVenta>();
        }
    
        public int codVenta { get; set; }
        public short montoTotal { get; set; }
        public short fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ComboVenta> T_ComboVenta { get; set; }
    }
}
